default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: openhunt_development

test:
  <<: *default
  database: openhunt_test

production:
  <<: *default
  database: openhunt_production
