some_config: "Hello"

featured_per_page: 10

base_timezone: "Pacific Time (US & Canada)"

include_analytics: false

site_launch: "Dec 18, 2015"

products_to_show: 20


# in minutes
project_edit_window: 20
