some_config: "Hello"

oauth_public_key: "Mmu8yzNpaSwZ9pZn-1p69wMOXl8"


featured_per_page: 10

base_timezone: "Pacific Time (US & Canada)"

include_analytics: false

site_launch: "Dec 14, 2015"

products_to_show: 20
